version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing Angular CLI..."
      - npm install -g @angular/cli@17
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Running Unit Tests with No-Sandbox..."
      # karma.conf.js에 정의한 ChromeHeadlessCI를 명시적으로 호출합니다.
      - ng test --no-watch --no-progress --browsers=ChromeHeadlessCI